# Teckin SP20 (USA model)
# GPIO13 = Button
# GPIO4  = Relay
# GPIO2  = Blue LED (inverted)
# GPIO0  = Red LED (inverted)
# GPIO12 = HLW8012 SEL Pin (inverted)
# GPIO5  = HLW8012 CF Pin
# GPIO14 = HLW8012 CF1 Pin


substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: teckin_sp20     # used internally.. e.g. living_room_lamp
  friendly_name: Teckin SP20   # displayed in HA.. e.g. Living Room Lamp
  ip_address: !secret teckin_sp20_ip


esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1

    
# web_server:
#   port: 80
  # https://esphomelib.com/esphomeyaml/components/web_server.html
  

logger:
  # https://esphome.io/components/logger


api:
  password: !secret esphome_api_password
  # https://esphome.io/components/api
  

ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


sensor:
  - platform: hlw8012
    # https://esphome.io/components/sensor/hlw8012.html
    # current, power, voltage can all use sensor options shown at https://esphome.io/components/sensor/#config-sensor
    sel_pin: 
      number: GPIO12
      inverted: True
    cf_pin: GPIO5
    cf1_pin: GPIO14
    current:
      name: ${friendly_name} Current
    power:
      name: ${friendly_name} Power
      id: ${device_name}_power
      filters:
        - multiply: 0.4545
    voltage:
      name: ${friendly_name} Voltage
    current_resistor: 0.001  # default 0.001
    voltage_divider: 910     # default 2351
    change_mode_every: 3     # default 8
    update_interval: 3s      # default 60s

  - platform: total_daily_energy
    # https://esphome.io/components/sensor/total_daily_energy.html
    name: ${friendly_name} Total Daily Energy
    power_id: ${device_name}_power
    filters:
      - multiply: 0.001   # convert Wh to kWh
    unit_of_measurement: kWh


time:
  - platform: homeassistant
    # https://esphome.io/components/time
    id: homeassistant_time


status_led:
  # https://esphome.io/components/status_led
  pin:
    number: GPIO0
    inverted: True


binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO13
    id: button
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
    internal: True
      

switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    id: blue_led
    pin:
      number: GPIO2
      inverted: True
    
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    pin: GPIO4
    name: ${friendly_name}
    id: relay
    # Tie Blue LED to relay
    on_turn_on:
    - switch.turn_on: blue_led
    on_turn_off:
    - switch.turn_off: blue_led
